### ISSUE TITLE
Is it possible to keep your osu open while downloading a map in a multi.

### ISSUE THREAD

**Issue by LuxeaYT** [jecsham/osukoko-chrome#16]
**Is your feature request related to a problem? Please describe.**
If I'm playing in an osu! multi lobby, I want to stay tabbed into my game and the download to happen seamlessly.

**Describe the solution you'd like**
I want a way to keep my browser minimized (ms is higher when the browser is open in the background) and I want osu! to stay tabbed in when clicking the in-game download button in a multi lobby

**Additional context**
I'm aware this probably isn't possible in a chrome extension but if it's possible by other means that would be great.

**Comment by jecsham** [comment]
Currently its not possible to perform this action with chrome extensions :(
